export const queryKeys = {
	CUSTOMER: "customer",
	PROJECT: "project",
	USER: "user",
	ASSIGNMENTS: "assignments",
	BUDGETS: "budgets",
	BUDGETS_TO_COMPLETE: "budgets_to_complete",
	CUSTOMERS: "customers",
	CUSTOMERS_WITHOUT_QUERY: "customers_without_query",
	FOLLOW_UPS: "follow_ups",
	NOTIFICATIONS: "notifications",
	PROJECTS: "projects",
	TASKS: "tasks",
	USERS: "users",
	USERS_WITHOUT_QUERY: "users_without_query",
	DISTRICT_REVENUE: "district_revenue",
	CUSTOMER_TYPE_REVENUE: "customer_type_revenue",
	VALUE_DISTRIBUTION: "value_distribution",
	BUDGET_ITEM_TYPE_REVENUE: "budget_item_type_revenue",
} as const;
